/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as WaitingRoomImport } from "./routes/waiting-room";
import { Route as MyPageImport } from "./routes/my-page";
import { Route as LoginImport } from "./routes/login";
import { Route as CreateVoteImport } from "./routes/create-vote";
import { Route as ChatImport } from "./routes/chat";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const WaitingRoomRoute = WaitingRoomImport.update({
  id: "/waiting-room",
  path: "/waiting-room",
  getParentRoute: () => rootRoute,
} as any);

const MyPageRoute = MyPageImport.update({
  id: "/my-page",
  path: "/my-page",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const CreateVoteRoute = CreateVoteImport.update({
  id: "/create-vote",
  path: "/create-vote",
  getParentRoute: () => rootRoute,
} as any);

const ChatRoute = ChatImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatImport;
      parentRoute: typeof rootRoute;
    };
    "/create-vote": {
      id: "/create-vote";
      path: "/create-vote";
      fullPath: "/create-vote";
      preLoaderRoute: typeof CreateVoteImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/my-page": {
      id: "/my-page";
      path: "/my-page";
      fullPath: "/my-page";
      preLoaderRoute: typeof MyPageImport;
      parentRoute: typeof rootRoute;
    };
    "/waiting-room": {
      id: "/waiting-room";
      path: "/waiting-room";
      fullPath: "/waiting-room";
      preLoaderRoute: typeof WaitingRoomImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/chat": typeof ChatRoute;
  "/create-vote": typeof CreateVoteRoute;
  "/login": typeof LoginRoute;
  "/my-page": typeof MyPageRoute;
  "/waiting-room": typeof WaitingRoomRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/chat": typeof ChatRoute;
  "/create-vote": typeof CreateVoteRoute;
  "/login": typeof LoginRoute;
  "/my-page": typeof MyPageRoute;
  "/waiting-room": typeof WaitingRoomRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/chat": typeof ChatRoute;
  "/create-vote": typeof CreateVoteRoute;
  "/login": typeof LoginRoute;
  "/my-page": typeof MyPageRoute;
  "/waiting-room": typeof WaitingRoomRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/chat"
    | "/create-vote"
    | "/login"
    | "/my-page"
    | "/waiting-room";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/chat" | "/create-vote" | "/login" | "/my-page" | "/waiting-room";
  id:
    | "__root__"
    | "/"
    | "/chat"
    | "/create-vote"
    | "/login"
    | "/my-page"
    | "/waiting-room";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ChatRoute: typeof ChatRoute;
  CreateVoteRoute: typeof CreateVoteRoute;
  LoginRoute: typeof LoginRoute;
  MyPageRoute: typeof MyPageRoute;
  WaitingRoomRoute: typeof WaitingRoomRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CreateVoteRoute: CreateVoteRoute,
  LoginRoute: LoginRoute,
  MyPageRoute: MyPageRoute,
  WaitingRoomRoute: WaitingRoomRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat",
        "/create-vote",
        "/login",
        "/my-page",
        "/waiting-room"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chat": {
      "filePath": "chat.tsx"
    },
    "/create-vote": {
      "filePath": "create-vote.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/my-page": {
      "filePath": "my-page.tsx"
    },
    "/waiting-room": {
      "filePath": "waiting-room.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
