name: Backend Deploy

on:
  push:
    branches:
      - dev
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # NestJS 빌드 과정

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version-file: ".nvmrc"

      # - name: Install pnpm
      #   run: npm install -g pnpm

      # - name: Install dependencies
      #   run: pnpm install
      #   working-directory: ${{ vars.BACK_SERVICE_PATH }}

      # - name: Build the project
      #   run: pnpm run build

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PEM_KEY }}" >> /tmp/deploy_key.pem && \
          chmod 400 /tmp/deploy_key.pem && \
          eval "$(ssh-agent -s)" && \
          ssh-add /tmp/deploy_key.pem

      - name: Deploy to server
        run: |
          ssh -i /tmp/deploy_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
            echo "Connected to the server"
            cd /app/web14-betting-duck
            git pull origin dev
            cd /app/web14-betting-duck/backend
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker compose up -d
          EOF

      - name: Notify deployment status
        if: success()
        run: echo "Deployment succeeded."

      - name: Notify deployment failure
        if: failure()
        run: echo "Deployment failed."
