name: Frontend Deploy

on:
  push:
    branches:
      - dev
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PEM_KEY }}" >> /tmp/deploy_key.pem && \
          chmod 400 /tmp/deploy_key.pem && \
          eval "$(ssh-agent -s)" && \
          ssh-add /tmp/deploy_key.pem

      - name: Deploy to server
        run: |
          ssh -i /tmp/deploy_key.pem -o StrictHostKeyChecking=no root@223.130.128.166 << EOF
            echo "Connected to the server"
            cd /app/web14-betting-duck
            git pull origin dev
            cd /app/web14-betting-duck/frontend
            echo "Install dependencies"
            pnpm install
            echo "Build the project"
            pnpm run build
          EOF

      - name: Notify deployment status
        if: success()
        run: echo "Deployment succeeded."

      - name: Notify deployment failure
        if: failure()
        run: echo "Deployment failed."
